#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : plasma-workspace
Version  : 5.23.90
Release  : 305
URL      : file:///aot/build/clearlinux/packages/plasma-workspace/plasma-workspace-v5.23.90.tar.gz
Source0  : file:///aot/build/clearlinux/packages/plasma-workspace/plasma-workspace-v5.23.90.tar.gz
Source1  : kde.pam
Source2  : kde-np.pam
Source3  : kscreensaver.pam
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: plasma-workspace-bin = %{version}-%{release}
Requires: plasma-workspace-data = %{version}-%{release}
Requires: plasma-workspace-lib = %{version}-%{release}
Requires: plasma-workspace-libexec = %{version}-%{release}
Requires: plasma-workspace-services = %{version}-%{release}
BuildRequires : NetworkManager-dev
BuildRequires : appstream-dev
BuildRequires : appstream-extras
BuildRequires : attica-dev
BuildRequires : baloo-dev
BuildRequires : breeze
BuildRequires : breeze-dev
BuildRequires : breeze-gtk
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : fftw-dev
BuildRequires : frameworkintegration-dev
BuildRequires : glibc-dev
BuildRequires : gmp-dev
BuildRequires : kactivities-dev
BuildRequires : kactivities-stats-dev
BuildRequires : karchive-dev
BuildRequires : kcmutils-dev
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfigwidgets-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdecoration-dev
BuildRequires : kded-dev
BuildRequires : kdelibs4support-dev
BuildRequires : kdesignerplugin-dev
BuildRequires : kdesu-dev
BuildRequires : kdoctools-dev
BuildRequires : kemoticons-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kguiaddons-dev
BuildRequires : kholidays-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kidletime-dev
BuildRequires : kinit-dev
BuildRequires : kio-dev
BuildRequires : kio-extras-dev
BuildRequires : kirigami2-dev
BuildRequires : kitemmodels-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : kjs-dev
BuildRequires : kjsembed-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kpackage-dev
BuildRequires : kparts-dev
BuildRequires : kpeople-dev
BuildRequires : kpty-dev
BuildRequires : kquickcharts-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : ksysguard
BuildRequires : ktexteditor-dev
BuildRequires : kunitconversion-dev
BuildRequires : kwayland-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwin-dev
BuildRequires : kwindowsystem-dev
BuildRequires : kxmlgui-dev
BuildRequires : layer-shell-qt-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libkscreen-dev
BuildRequires : libksysguard-dev
BuildRequires : libqalculate-dev
BuildRequires : libxcb-dev
BuildRequires : mesa-dev
BuildRequires : mpfr-dev
BuildRequires : networkmanager-qt-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-wayland-protocols-dev
BuildRequires : plasma-workspace-wallpapers
BuildRequires : prison-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-staticdev
BuildRequires : qtdeclarative-dev
BuildRequires : qttools-dev
BuildRequires : qtwayland-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : syntax-highlighting-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
StartKDE
Startup script used on X
StartPlasmaCompositor + StartPlasma
Startup script used on Wayland.
StartPlasmaCompostior is run before kwin and sets up kwin's env
StartPlasma is then invoked by kwin

%package bin
Summary: bin components for the plasma-workspace package.
Group: Binaries
Requires: plasma-workspace-data = %{version}-%{release}
Requires: plasma-workspace-libexec = %{version}-%{release}
Requires: plasma-workspace-services = %{version}-%{release}

%description bin
bin components for the plasma-workspace package.


%package data
Summary: data components for the plasma-workspace package.
Group: Data

%description data
data components for the plasma-workspace package.


%package dev
Summary: dev components for the plasma-workspace package.
Group: Development
Requires: plasma-workspace-lib = %{version}-%{release}
Requires: plasma-workspace-bin = %{version}-%{release}
Requires: plasma-workspace-data = %{version}-%{release}
Provides: plasma-workspace-devel = %{version}-%{release}
Requires: plasma-workspace = %{version}-%{release}

%description dev
dev components for the plasma-workspace package.


%package doc
Summary: doc components for the plasma-workspace package.
Group: Documentation

%description doc
doc components for the plasma-workspace package.


%package lib
Summary: lib components for the plasma-workspace package.
Group: Libraries
Requires: plasma-workspace-data = %{version}-%{release}
Requires: plasma-workspace-libexec = %{version}-%{release}

%description lib
lib components for the plasma-workspace package.


%package libexec
Summary: libexec components for the plasma-workspace package.
Group: Default

%description libexec
libexec components for the plasma-workspace package.


%package services
Summary: services components for the plasma-workspace package.
Group: Systemd services

%description services
services components for the plasma-workspace package.


%prep
%setup -q -n plasma-workspace
cd %{_builddir}/plasma-workspace

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643421866
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
%cmake .. -DKDE_INSTALL_CONFDIR=/usr/share/xdg
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1643421866
rm -rf %{buildroot}
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/share/pam.d
install -m644 %{_sourcedir}/kde.pam %{buildroot}/usr/share/pam.d/kde
mkdir -p %{buildroot}/usr/share/pam.d
install -m644 %{_sourcedir}/kde-np.pam %{buildroot}/usr/share/pam.d/kde-np
mkdir -p %{buildroot}/usr/share/pam.d
install -m644 %{_sourcedir}/kscreensaver.pam %{buildroot}/usr/share/pam.d/kscreensaver

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gmenudbusmenuproxy
/usr/bin/kcminit
/usr/bin/kcminit_startup
/usr/bin/kcolorschemeeditor
/usr/bin/kde-systemd-start-condition
/usr/bin/kfontinst
/usr/bin/kfontview
/usr/bin/klipper
/usr/bin/krunner
/usr/bin/ksmserver
/usr/bin/ksplashqml
/usr/bin/lookandfeeltool
/usr/bin/plasma-apply-colorscheme
/usr/bin/plasma-apply-cursortheme
/usr/bin/plasma-apply-desktoptheme
/usr/bin/plasma-apply-lookandfeel
/usr/bin/plasma-apply-wallpaperimage
/usr/bin/plasma-interactiveconsole
/usr/bin/plasma-shutdown
/usr/bin/plasma_session
/usr/bin/plasma_waitforname
/usr/bin/plasmashell
/usr/bin/plasmawindowed
/usr/bin/startplasma-wayland
/usr/bin/startplasma-x11
/usr/bin/systemmonitor
/usr/bin/xembedsniproxy
/usr/lib64/kconf_update_bin/krunnerglobalshortcuts
/usr/lib64/kconf_update_bin/krunnerhistory

%files data
%defattr(-,root,root,-)
/usr/share/applications/kcm_autostart.desktop
/usr/share/applications/kcm_colors.desktop
/usr/share/applications/kcm_cursortheme.desktop
/usr/share/applications/kcm_desktoptheme.desktop
/usr/share/applications/kcm_fontinst.desktop
/usr/share/applications/kcm_fonts.desktop
/usr/share/applications/kcm_formats.desktop
/usr/share/applications/kcm_icons.desktop
/usr/share/applications/kcm_lookandfeel.desktop
/usr/share/applications/kcm_nightcolor.desktop
/usr/share/applications/kcm_notifications.desktop
/usr/share/applications/kcm_style.desktop
/usr/share/applications/kcm_translations.desktop
/usr/share/applications/kcm_users.desktop
/usr/share/applications/org.kde.kcolorschemeeditor.desktop
/usr/share/applications/org.kde.kfontview.desktop
/usr/share/applications/org.kde.klipper.desktop
/usr/share/applications/org.kde.plasmashell.desktop
/usr/share/applications/org.kde.plasmawindowed.desktop
/usr/share/applications/org.kde.systemmonitor.desktop
/usr/share/config.kcfg/colorssettings.kcfg
/usr/share/config.kcfg/cursorthemesettings.kcfg
/usr/share/config.kcfg/fontssettings.kcfg
/usr/share/config.kcfg/freespacenotifier.kcfg
/usr/share/config.kcfg/iconssettingsbase.kcfg
/usr/share/config.kcfg/lookandfeelsettings.kcfg
/usr/share/config.kcfg/stylesettings.kcfg
/usr/share/dbus-1/interfaces/com.canonical.AppMenu.Registrar.xml
/usr/share/dbus-1/interfaces/org.kde.KSMServerInterface.xml
/usr/share/dbus-1/interfaces/org.kde.KSplash.xml
/usr/share/dbus-1/interfaces/org.kde.PlasmaShell.xml
/usr/share/dbus-1/interfaces/org.kde.kappmenu.xml
/usr/share/dbus-1/interfaces/org.kde.krunner.App.xml
/usr/share/dbus-1/services/org.kde.KSplash.service
/usr/share/dbus-1/services/org.kde.LogoutPrompt.service
/usr/share/dbus-1/services/org.kde.Shutdown.service
/usr/share/dbus-1/services/org.kde.fontinst.service
/usr/share/dbus-1/services/org.kde.krunner.service
/usr/share/dbus-1/services/org.kde.plasma.Notifications.service
/usr/share/dbus-1/services/org.kde.runners.baloo.service
/usr/share/dbus-1/system-services/org.kde.fontinst.service
/usr/share/dbus-1/system.d/org.kde.fontinst.conf
/usr/share/desktop-directories/kf5-development-translation.directory
/usr/share/desktop-directories/kf5-development-webdevelopment.directory
/usr/share/desktop-directories/kf5-development.directory
/usr/share/desktop-directories/kf5-editors.directory
/usr/share/desktop-directories/kf5-edu-languages.directory
/usr/share/desktop-directories/kf5-edu-mathematics.directory
/usr/share/desktop-directories/kf5-edu-miscellaneous.directory
/usr/share/desktop-directories/kf5-edu-science.directory
/usr/share/desktop-directories/kf5-edu-tools.directory
/usr/share/desktop-directories/kf5-education.directory
/usr/share/desktop-directories/kf5-games-arcade.directory
/usr/share/desktop-directories/kf5-games-board.directory
/usr/share/desktop-directories/kf5-games-card.directory
/usr/share/desktop-directories/kf5-games-kids.directory
/usr/share/desktop-directories/kf5-games-logic.directory
/usr/share/desktop-directories/kf5-games-roguelikes.directory
/usr/share/desktop-directories/kf5-games-strategy.directory
/usr/share/desktop-directories/kf5-games.directory
/usr/share/desktop-directories/kf5-graphics.directory
/usr/share/desktop-directories/kf5-internet-terminal.directory
/usr/share/desktop-directories/kf5-internet.directory
/usr/share/desktop-directories/kf5-main.directory
/usr/share/desktop-directories/kf5-more.directory
/usr/share/desktop-directories/kf5-multimedia.directory
/usr/share/desktop-directories/kf5-network.directory
/usr/share/desktop-directories/kf5-office.directory
/usr/share/desktop-directories/kf5-science.directory
/usr/share/desktop-directories/kf5-settingsmenu.directory
/usr/share/desktop-directories/kf5-system-terminal.directory
/usr/share/desktop-directories/kf5-system.directory
/usr/share/desktop-directories/kf5-toys.directory
/usr/share/desktop-directories/kf5-unknown.directory
/usr/share/desktop-directories/kf5-utilities-accessibility.directory
/usr/share/desktop-directories/kf5-utilities-desktop.directory
/usr/share/desktop-directories/kf5-utilities-file.directory
/usr/share/desktop-directories/kf5-utilities-peripherals.directory
/usr/share/desktop-directories/kf5-utilities-pim.directory
/usr/share/desktop-directories/kf5-utilities-xutils.directory
/usr/share/desktop-directories/kf5-utilities.directory
/usr/share/icons/hicolor/128x128/mimetypes/fonts-package.png
/usr/share/icons/hicolor/16x16/apps/kfontview.png
/usr/share/icons/hicolor/16x16/mimetypes/fonts-package.png
/usr/share/icons/hicolor/22x22/apps/kfontview.png
/usr/share/icons/hicolor/22x22/mimetypes/fonts-package.png
/usr/share/icons/hicolor/32x32/apps/kfontview.png
/usr/share/icons/hicolor/32x32/mimetypes/fonts-package.png
/usr/share/icons/hicolor/48x48/apps/kfontview.png
/usr/share/icons/hicolor/48x48/mimetypes/fonts-package.png
/usr/share/icons/hicolor/64x64/apps/kfontview.png
/usr/share/icons/hicolor/64x64/mimetypes/fonts-package.png
/usr/share/icons/hicolor/scalable/apps/preferences-desktop-font-installer.svgz
/usr/share/kconf_update/delete_cursor_old_default_size.pl
/usr/share/kconf_update/delete_cursor_old_default_size.upd
/usr/share/kconf_update/icons_remove_effects.upd
/usr/share/kconf_update/krunnerglobalshortcuts2.upd
/usr/share/kconf_update/krunnerhistory.upd
/usr/share/kconf_update/style_widgetstyle_default_breeze.pl
/usr/share/kconf_update/style_widgetstyle_default_breeze.upd
/usr/share/kfontinst/icons/hicolor/16x16/actions/addfont.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/font-disable.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/font-enable.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/fontstatus.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/addfont.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/font-disable.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/font-enable.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/fontstatus.png
/usr/share/kglobalaccel/org.kde.krunner.desktop
/usr/share/kio_desktop/directory.desktop
/usr/share/kio_desktop/directory.trash
/usr/share/knotifications5/devicenotifications.notifyrc
/usr/share/knotifications5/freespacenotifier.notifyrc
/usr/share/knotifications5/phonon.notifyrc
/usr/share/knsrcfiles/colorschemes.knsrc
/usr/share/knsrcfiles/gtk_themes.knsrc
/usr/share/knsrcfiles/icons.knsrc
/usr/share/knsrcfiles/kfontinst.knsrc
/usr/share/knsrcfiles/lookandfeel.knsrc
/usr/share/knsrcfiles/plasma-themes.knsrc
/usr/share/knsrcfiles/plasmoids.knsrc
/usr/share/knsrcfiles/wallpaper-mobile.knsrc
/usr/share/knsrcfiles/wallpaper.knsrc
/usr/share/knsrcfiles/wallpaperplugin.knsrc
/usr/share/knsrcfiles/xcursor.knsrc
/usr/share/konqsidebartng/virtual_folders/services/fonts.desktop
/usr/share/kpackage/kcms/kcm_autostart/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_colors/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_cursortheme/contents/ui/Delegate.qml
/usr/share/kpackage/kcms/kcm_cursortheme/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/Hand.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/ThemePreview.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_fonts/contents/ui/FontWidget.qml
/usr/share/kpackage/kcms/kcm_fonts/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_formats/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_icons/contents/ui/IconSizePopup.qml
/usr/share/kpackage/kcms/kcm_icons/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_lookandfeel/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/LocationsFixedView.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/NumberField.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/TimeField.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/TimingsView.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/ApplicationConfiguration.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/PopupPositionPage.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/ScreenPositionSelector.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/SourcesPage.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_style/contents/ui/EffectSettingsPopup.qml
/usr/share/kpackage/kcms/kcm_style/contents/ui/GtkStylePage.qml
/usr/share/kpackage/kcms/kcm_style/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_translations/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/ChangePassword.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/ChangeWalletPassword.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/CreateUser.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/FingerprintDialog.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/FingerprintProgressCircle.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/UserDetailsPage.qml
/usr/share/kpackage/kcms/kcm_users/contents/ui/main.qml
/usr/share/krunner/dbusplugins/plasma-runner-baloosearch.desktop
/usr/share/kservices5/ServiceMenus/installfont.desktop
/usr/share/kservices5/ServiceMenus/setaswallpaper.desktop
/usr/share/kservices5/fontthumbnail.desktop
/usr/share/kservicetypes5/phononbackend.desktop
/usr/share/kservicetypes5/plasma-layouttemplate.desktop
/usr/share/ksplash/Themes/Classic/FadeIn.qml
/usr/share/ksplash/Themes/Classic/Preview.png
/usr/share/ksplash/Themes/Classic/Theme.rc
/usr/share/ksplash/Themes/Classic/images/background.png
/usr/share/ksplash/Themes/Classic/images/icon1.png
/usr/share/ksplash/Themes/Classic/images/icon2.png
/usr/share/ksplash/Themes/Classic/images/icon3.png
/usr/share/ksplash/Themes/Classic/images/icon4.png
/usr/share/ksplash/Themes/Classic/images/icon5.png
/usr/share/ksplash/Themes/Classic/images/rectangle.png
/usr/share/ksplash/Themes/Classic/main.qml
/usr/share/ksplash/Themes/Minimalistic/Preview.png
/usr/share/ksplash/Themes/Minimalistic/Theme.rc
/usr/share/ksplash/Themes/Minimalistic/images/kdegear.png
/usr/share/ksplash/Themes/Minimalistic/images/kdeletter.png
/usr/share/ksplash/Themes/Minimalistic/images/kdelogo-contrast.png
/usr/share/ksplash/Themes/Minimalistic/images/kdelogo.png
/usr/share/ksplash/Themes/Minimalistic/images/kdemask.png
/usr/share/ksplash/Themes/Minimalistic/main.qml
/usr/share/ksplash/Themes/None/Theme.rc
/usr/share/kstyle/themes/qtcde.themerc
/usr/share/kstyle/themes/qtcleanlooks.themerc
/usr/share/kstyle/themes/qtgtk.themerc
/usr/share/kstyle/themes/qtmotif.themerc
/usr/share/kstyle/themes/qtplastique.themerc
/usr/share/kstyle/themes/qtwindows.themerc
/usr/share/kxmlgui5/kfontview/kfontviewpart.rc
/usr/share/kxmlgui5/kfontview/kfontviewui.rc
/usr/share/metainfo/org.kde.breeze.desktop.appdata.xml
/usr/share/metainfo/org.kde.breezedark.desktop.appdata.xml
/usr/share/metainfo/org.kde.breezetwilight.desktop.appdata.xml
/usr/share/metainfo/org.kde.color.appdata.xml
/usr/share/metainfo/org.kde.image.appdata.xml
/usr/share/metainfo/org.kde.plasma.activitybar.appdata.xml
/usr/share/metainfo/org.kde.plasma.analogclock.appdata.xml
/usr/share/metainfo/org.kde.plasma.appmenu.appdata.xml
/usr/share/metainfo/org.kde.plasma.battery.appdata.xml
/usr/share/metainfo/org.kde.plasma.calendar.appdata.xml
/usr/share/metainfo/org.kde.plasma.clipboard.appdata.xml
/usr/share/metainfo/org.kde.plasma.devicenotifier.appdata.xml
/usr/share/metainfo/org.kde.plasma.digitalclock.appdata.xml
/usr/share/metainfo/org.kde.plasma.lock_logout.appdata.xml
/usr/share/metainfo/org.kde.plasma.manage-inputmethod.appdata.xml
/usr/share/metainfo/org.kde.plasma.mediacontroller.appdata.xml
/usr/share/metainfo/org.kde.plasma.notifications.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.cpu.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.cpucore.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.diskactivity.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.diskusage.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.memory.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemmonitor.net.appdata.xml
/usr/share/metainfo/org.kde.plasma.systemtray.appdata.xml
/usr/share/metainfo/org.kde.slideshow.appdata.xml
/usr/share/pam.d/kde
/usr/share/pam.d/kde-np
/usr/share/pam.d/kscreensaver
"/usr/share/plasma/avatars/Artist Konqi.png"
"/usr/share/plasma/avatars/Bookworm Konqi.png"
"/usr/share/plasma/avatars/Boss Konqi.png"
"/usr/share/plasma/avatars/Bug Catcher Konqi.png"
"/usr/share/plasma/avatars/Card Shark Konqi.png"
"/usr/share/plasma/avatars/Hacker Konqi.png"
"/usr/share/plasma/avatars/Journalist Konqi.png"
/usr/share/plasma/avatars/Katie.png
/usr/share/plasma/avatars/Konqi.png
"/usr/share/plasma/avatars/Mechanic Konqi.png"
"/usr/share/plasma/avatars/Messenger Konqi.png"
"/usr/share/plasma/avatars/Musician Konqi.png"
"/usr/share/plasma/avatars/Office Worker Konqi.png"
"/usr/share/plasma/avatars/PC Builder Konqi.png"
"/usr/share/plasma/avatars/Scientist Konqi.png"
"/usr/share/plasma/avatars/Teacher Konqi.png"
"/usr/share/plasma/avatars/Virtual Reality Konqi.png"
"/usr/share/plasma/avatars/photos/Air Balloon.png"
"/usr/share/plasma/avatars/photos/Air Balloon.png.license"
/usr/share/plasma/avatars/photos/Astronaut.png
/usr/share/plasma/avatars/photos/Astronaut.png.license
/usr/share/plasma/avatars/photos/Books.png
/usr/share/plasma/avatars/photos/Books.png.license
/usr/share/plasma/avatars/photos/Brushes.png
/usr/share/plasma/avatars/photos/Brushes.png.license
/usr/share/plasma/avatars/photos/Bulb.png
/usr/share/plasma/avatars/photos/Bulb.png.license
/usr/share/plasma/avatars/photos/Car.png
/usr/share/plasma/avatars/photos/Car.png.license
/usr/share/plasma/avatars/photos/Cat.png
/usr/share/plasma/avatars/photos/Cat.png.license
/usr/share/plasma/avatars/photos/Chameleon.png
/usr/share/plasma/avatars/photos/Chamelon.png.license
/usr/share/plasma/avatars/photos/Cocktail.png
/usr/share/plasma/avatars/photos/Cocktail.png.license
/usr/share/plasma/avatars/photos/Dog.png
/usr/share/plasma/avatars/photos/Dog.png.license
/usr/share/plasma/avatars/photos/Fish.png
/usr/share/plasma/avatars/photos/Fish.png.license
/usr/share/plasma/avatars/photos/Gamepad.png
/usr/share/plasma/avatars/photos/Gamepad.png.license
/usr/share/plasma/avatars/photos/Owl.png
/usr/share/plasma/avatars/photos/Owl.png.license
/usr/share/plasma/avatars/photos/Pancakes.png
/usr/share/plasma/avatars/photos/Pancakes.png.license
/usr/share/plasma/avatars/photos/Parrot.png
/usr/share/plasma/avatars/photos/Parrot.png.license
/usr/share/plasma/avatars/photos/Pencils.png
/usr/share/plasma/avatars/photos/Pencils.png.license
/usr/share/plasma/avatars/photos/Shuttle.png
/usr/share/plasma/avatars/photos/Shuttle.png.license
/usr/share/plasma/avatars/photos/Soccer.png
/usr/share/plasma/avatars/photos/Soccer.png.license
/usr/share/plasma/avatars/photos/Sunflower.png
/usr/share/plasma/avatars/photos/Sunflower.png.license
/usr/share/plasma/avatars/photos/Sushi.png
/usr/share/plasma/avatars/photos/Sushi.png.license
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/ActionButton.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/Battery.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/Clock.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/SessionManagementScreen.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/UserDelegate.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/UserList.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/VirtualKeyboard.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/VirtualKeyboard_wayland.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/WallpaperFader.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/artwork/README.txt
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/artwork/logout_primary.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/artwork/restart_primary.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/artwork/shutdown_primary.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/defaults
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/desktopswitcher/DesktopSwitcher.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/LockOsd.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/LockScreen.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/LockScreenUi.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/MainBlock.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/MediaControls.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/config.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen/config.xml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/logout/Logout.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/logout/LogoutButton.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/logout/timer.js
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/osd/Osd.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/osd/OsdItem.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/desktopswitcher.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/fullscreenpreview.jpg
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/lockscreen.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/loginmanager.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/preview.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/runcommand.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/splash.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/userswitcher.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/windowdecoration.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/previews/windowswitcher.png
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/runcommand/RunCommand.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/Splash.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/images/busywidget.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/images/kde.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/images/plasma.svgz
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/systemdialog/SystemDialog.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/windowswitcher/WindowSwitcher.qml
/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/metadata.json
/usr/share/plasma/look-and-feel/org.kde.breezedark.desktop/contents/defaults
/usr/share/plasma/look-and-feel/org.kde.breezedark.desktop/contents/previews/fullscreenpreview.jpg
/usr/share/plasma/look-and-feel/org.kde.breezedark.desktop/contents/previews/preview.png
/usr/share/plasma/look-and-feel/org.kde.breezedark.desktop/metadata.json
/usr/share/plasma/look-and-feel/org.kde.breezetwilight.desktop/contents/defaults
/usr/share/plasma/look-and-feel/org.kde.breezetwilight.desktop/contents/previews/fullscreenpreview.jpg
/usr/share/plasma/look-and-feel/org.kde.breezetwilight.desktop/contents/previews/preview.png
/usr/share/plasma/look-and-feel/org.kde.breezetwilight.desktop/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.activitybar/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.activitybar/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/Hand.qml
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.analogclock/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/ui/MenuDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.appmenu/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/BadgeOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/BatteryItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/BrightnessItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/InhibitionHint.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/PopupDialog.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/PowerManagementItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/PowerProfileItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/logic.js
/usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.battery/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/contents/images/mini-calendar.svgz
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.calendar/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/BarcodePage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/ClipboardItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/ClipboardPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/DelegateToolButtons.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/EditPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/ImageItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/Menu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/TextItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/UrlItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/clipboard.qml
/usr/share/plasma/plasmoids/org.kde.plasma.clipboard/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.devicenotifier/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.devicenotifier/contents/ui/DeviceItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.devicenotifier/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.devicenotifier/contents/ui/devicenotifier.qml
/usr/share/plasma/plasmoids/org.kde.plasma.devicenotifier/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/CalendarView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/DigitalClock.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/MonthMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/configCalendar.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/configTimeZones.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.icon/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.icon/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.icon/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/contents/ui/data.js
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/contents/ui/lockout.qml
/usr/share/plasma/plasmoids/org.kde.plasma.lock_logout/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.manage-inputmethod/contents/ui/manage-inputmethod.qml
/usr/share/plasma/plasmoids/org.kde.plasma.manage-inputmethod/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/ExpandedRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/DraggableDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/DraggableFileArea.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/EditContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/JobDetails.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/JobItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationPopup.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationReplyField.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/SelectableLabel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/ThumbnailStrip.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/PulseAudio.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/qmldir
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notifications/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/applet/CompactApplet.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ConfigEntries.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/CurrentItemHighLight.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ExpandedRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ExpanderArrow.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/HiddenItemsView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/PlasmoidPopupsContainer.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/SystemTrayState.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/AbstractItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/ItemLoader.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/PlasmoidItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/PulseAnimation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/StatusNotifierItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.cpu/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.cpu/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.cpucore/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.cpucore/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.diskactivity/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.diskactivity/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.diskusage/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.diskusage/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.memory/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.memory/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.net/contents/config/faceproperties
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor.net/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/config/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/config/ConfigSensors.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/config/FaceDetails.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.systemtray/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.systemtray/metadata.json
/usr/share/plasma/services/activities.operations
/usr/share/plasma/services/applicationjobs.operations
/usr/share/plasma/services/apps.operations
/usr/share/plasma/services/hotplug.operations
/usr/share/plasma/services/modifierkeystate.operations
/usr/share/plasma/services/mpris2.operations
/usr/share/plasma/services/notifications.operations
/usr/share/plasma/services/org.kde.places.operations
/usr/share/plasma/services/org.kde.plasma.clipboard.operations
/usr/share/plasma/services/packagekit.operations
/usr/share/plasma/services/powermanagementservice.operations
/usr/share/plasma/services/soliddevice.operations
/usr/share/plasma/services/statusnotifieritem.operations
/usr/share/plasma/wallpapers/org.kde.color/contents/config/main.xml
/usr/share/plasma/wallpapers/org.kde.color/contents/ui/config.qml
/usr/share/plasma/wallpapers/org.kde.color/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.color/metadata.json
/usr/share/plasma/wallpapers/org.kde.image/contents/config/main.xml
/usr/share/plasma/wallpapers/org.kde.image/contents/ui/WallpaperDelegate.qml
/usr/share/plasma/wallpapers/org.kde.image/contents/ui/config.qml
/usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.image/metadata.json
/usr/share/plasma/wallpapers/org.kde.image/setaswallpaper.desktop.in
/usr/share/plasma/wallpapers/org.kde.slideshow/contents/config/main.xml
/usr/share/plasma/wallpapers/org.kde.slideshow/contents/ui/WallpaperDelegate.qml
/usr/share/plasma/wallpapers/org.kde.slideshow/contents/ui/config.qml
/usr/share/plasma/wallpapers/org.kde.slideshow/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.slideshow/metadata.json
/usr/share/polkit-1/actions/org.kde.fontinst.policy
/usr/share/qlogging-categories5/kcm_translations.categories
/usr/share/qlogging-categories5/kcmusers.categories
/usr/share/qlogging-categories5/klipper.categories
/usr/share/qlogging-categories5/libnotificationmanager.categories
/usr/share/qlogging-categories5/myproject.categories
/usr/share/qlogging-categories5/plasma-workspace.categories
/usr/share/sddm/themes/breeze/Background.qml
/usr/share/sddm/themes/breeze/BreezeMenuStyle.qml
/usr/share/sddm/themes/breeze/KeyboardButton.qml
/usr/share/sddm/themes/breeze/Login.qml
/usr/share/sddm/themes/breeze/Main.qml
/usr/share/sddm/themes/breeze/SessionButton.qml
/usr/share/sddm/themes/breeze/components/ActionButton.qml
/usr/share/sddm/themes/breeze/components/Battery.qml
/usr/share/sddm/themes/breeze/components/Clock.qml
/usr/share/sddm/themes/breeze/components/SessionManagementScreen.qml
/usr/share/sddm/themes/breeze/components/UserDelegate.qml
/usr/share/sddm/themes/breeze/components/UserList.qml
/usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml
/usr/share/sddm/themes/breeze/components/VirtualKeyboard_wayland.qml
/usr/share/sddm/themes/breeze/components/WallpaperFader.qml
/usr/share/sddm/themes/breeze/components/artwork/logout_primary.svgz
/usr/share/sddm/themes/breeze/components/artwork/restart_primary.svgz
/usr/share/sddm/themes/breeze/components/artwork/shutdown_primary.svgz
/usr/share/sddm/themes/breeze/default-logo.svg
/usr/share/sddm/themes/breeze/faces/.face.icon
/usr/share/sddm/themes/breeze/metadata.desktop
/usr/share/sddm/themes/breeze/preview.png
/usr/share/sddm/themes/breeze/theme.conf
/usr/share/solid/actions/test-predicate-openinwindow.desktop
/usr/share/wayland-sessions/plasmawayland.desktop
/usr/share/xdg/autostart/gmenudbusmenuproxy.desktop
/usr/share/xdg/autostart/klipper.desktop
/usr/share/xdg/autostart/org.kde.plasmashell.desktop
/usr/share/xdg/autostart/xembedsniproxy.desktop
/usr/share/xdg/plasmanotifyrc
/usr/share/xdg/taskmanagerrulesrc
/usr/share/xsessions/plasma.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/colorcorrect/colorcorrect_export.h
/usr/include/colorcorrect/colorcorrectconstants.h
/usr/include/colorcorrect/compositorcoloradaptor.h
/usr/include/colorcorrect/geolocator.h
/usr/include/kworkspace5/autostartscriptdesktopfile.h
/usr/include/kworkspace5/config-libkworkspace.h
/usr/include/kworkspace5/kdisplaymanager.h
/usr/include/kworkspace5/kworkspace.h
/usr/include/kworkspace5/kworkspace_export.h
/usr/include/kworkspace5/sessionmanagement.h
/usr/include/kworkspace5/updatelaunchenvjob.h
/usr/include/notificationmanager/badgesettings.h
/usr/include/notificationmanager/behaviorsettings.h
/usr/include/notificationmanager/donotdisturbsettings.h
/usr/include/notificationmanager/job.h
/usr/include/notificationmanager/jobsettings.h
/usr/include/notificationmanager/jobsmodel.h
/usr/include/notificationmanager/notification.h
/usr/include/notificationmanager/notificationmanager_export.h
/usr/include/notificationmanager/notifications.h
/usr/include/notificationmanager/notificationsettings.h
/usr/include/notificationmanager/server.h
/usr/include/notificationmanager/settings.h
/usr/include/plasma/geolocation/geolocation_export.h
/usr/include/plasma/geolocation/geolocationprovider.h
/usr/include/plasma/weather/ion.h
/usr/include/plasma/weather/ion_export.h
/usr/include/taskmanager/abstracttasksmodel.h
/usr/include/taskmanager/abstracttasksmodeliface.h
/usr/include/taskmanager/abstracttasksproxymodeliface.h
/usr/include/taskmanager/abstractwindowtasksmodel.h
/usr/include/taskmanager/activityinfo.h
/usr/include/taskmanager/concatenatetasksproxymodel.h
/usr/include/taskmanager/flattentaskgroupsproxymodel.h
/usr/include/taskmanager/launchertasksmodel.h
/usr/include/taskmanager/startuptasksmodel.h
/usr/include/taskmanager/taskfilterproxymodel.h
/usr/include/taskmanager/taskgroupingproxymodel.h
/usr/include/taskmanager/taskmanager_export.h
/usr/include/taskmanager/tasksmodel.h
/usr/include/taskmanager/tasktools.h
/usr/include/taskmanager/virtualdesktopinfo.h
/usr/include/taskmanager/waylandstartuptasksmodel.h
/usr/include/taskmanager/waylandtasksmodel.h
/usr/include/taskmanager/windowtasksmodel.h
/usr/include/taskmanager/xstartuptasksmodel.h
/usr/include/taskmanager/xwindowtasksmodel.h
/usr/lib64/cmake/KRunnerAppDBusInterface/KRunnerAppDBusInterfaceConfig.cmake
/usr/lib64/cmake/KSMServerDBusInterface/KSMServerDBusInterfaceConfig.cmake
/usr/lib64/cmake/LibColorCorrect/LibColorCorrectConfig.cmake
/usr/lib64/cmake/LibColorCorrect/LibColorCorrectConfigVersion.cmake
/usr/lib64/cmake/LibColorCorrect/LibColorCorrectLibraryTargets-none.cmake
/usr/lib64/cmake/LibColorCorrect/LibColorCorrectLibraryTargets.cmake
/usr/lib64/cmake/LibKWorkspace/LibKWorkspaceConfig.cmake
/usr/lib64/cmake/LibKWorkspace/LibKWorkspaceConfigVersion.cmake
/usr/lib64/cmake/LibKWorkspace/LibKWorkspaceLibraryTargets-none.cmake
/usr/lib64/cmake/LibKWorkspace/LibKWorkspaceLibraryTargets.cmake
/usr/lib64/cmake/LibNotificationManager/LibNotificationManagerConfig.cmake
/usr/lib64/cmake/LibNotificationManager/LibNotificationManagerConfigVersion.cmake
/usr/lib64/cmake/LibNotificationManager/LibNotificationManagerLibraryTargets-none.cmake
/usr/lib64/cmake/LibNotificationManager/LibNotificationManagerLibraryTargets.cmake
/usr/lib64/cmake/LibTaskManager/LibTaskManagerConfig.cmake
/usr/lib64/cmake/LibTaskManager/LibTaskManagerConfigVersion.cmake
/usr/lib64/cmake/LibTaskManager/LibTaskManagerLibraryTargets-none.cmake
/usr/lib64/cmake/LibTaskManager/LibTaskManagerLibraryTargets.cmake
/usr/lib64/libcolorcorrect.so
/usr/lib64/libkfontinst.so
/usr/lib64/libkfontinstui.so
/usr/lib64/libkrdb.so
/usr/lib64/libkworkspace5.so
/usr/lib64/libnotificationmanager.so
/usr/lib64/libplasma-geolocation-interface.so
/usr/lib64/libtaskmanager.so
/usr/lib64/libweather_ion.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_1.png
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_2.png
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_3.png
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_4.png
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_5.png
/usr/share/doc/HTML/en/PolicyKit-kde/authdialog_6.png
/usr/share/doc/HTML/en/PolicyKit-kde/authorization.docbook
/usr/share/doc/HTML/en/PolicyKit-kde/authorization_1.png
/usr/share/doc/HTML/en/PolicyKit-kde/authorization_2.png
/usr/share/doc/HTML/en/PolicyKit-kde/authorizationagent.docbook
/usr/share/doc/HTML/en/PolicyKit-kde/howitworks.docbook
/usr/share/doc/HTML/en/PolicyKit-kde/index.cache.bz2
/usr/share/doc/HTML/en/PolicyKit-kde/index.docbook
/usr/share/doc/HTML/en/PolicyKit-kde/introduction.docbook
/usr/share/doc/HTML/en/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/en/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/colors/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/edit-undo.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/main.png
/usr/share/doc/HTML/en/kcontrol/fontinst/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/en/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/en/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/en/kcontrol/fonts/main.png
/usr/share/doc/HTML/en/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/formats/index.docbook
/usr/share/doc/HTML/en/kcontrol/icons/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/icons/edit-undo.png
/usr/share/doc/HTML/en/kcontrol/icons/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/icons/index.docbook
/usr/share/doc/HTML/en/kcontrol/icons/main.png
/usr/share/doc/HTML/en/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/en/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/en/kcontrol/notifications/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/notifications/index.docbook
/usr/share/doc/HTML/en/kcontrol/screenlocker/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/screenlocker/index.docbook
/usr/share/doc/HTML/en/kcontrol/translations/go-top.png
/usr/share/doc/HTML/en/kcontrol/translations/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/translations/index.docbook
/usr/share/doc/HTML/en/kcontrol/translations/list-remove.png
/usr/share/doc/HTML/en/klipper/index.cache.bz2
/usr/share/doc/HTML/en/klipper/index.docbook
/usr/share/doc/HTML/en/klipper/klipper-widget.png
/usr/share/doc/HTML/en/klipper/screenshot.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcolorcorrect.so.5
/usr/lib64/libcolorcorrect.so.5.24.80
/usr/lib64/libkfontinst.so.5
/usr/lib64/libkfontinst.so.5.24.80
/usr/lib64/libkfontinstui.so.5
/usr/lib64/libkfontinstui.so.5.24.80
/usr/lib64/libkworkspace5.so.5
/usr/lib64/libkworkspace5.so.5.24.80
/usr/lib64/libnotificationmanager.so.1
/usr/lib64/libnotificationmanager.so.5.24.80
/usr/lib64/libplasma-geolocation-interface.so.5
/usr/lib64/libplasma-geolocation-interface.so.5.24.80
/usr/lib64/libtaskmanager.so.5.24.80
/usr/lib64/libtaskmanager.so.6
/usr/lib64/libweather_ion.so.7
/usr/lib64/libweather_ion.so.7.0.0
/usr/lib64/qt5/plugins/fontthumbnail.so
/usr/lib64/qt5/plugins/kcm_fontinst.so
/usr/lib64/qt5/plugins/kf5/kded/appmenu.so
/usr/lib64/qt5/plugins/kf5/kded/colorcorrectlocationupdater.so
/usr/lib64/qt5/plugins/kf5/kded/desktopnotifier.so
/usr/lib64/qt5/plugins/kf5/kded/freespacenotifier.so
/usr/lib64/qt5/plugins/kf5/kded/ksysguard.so
/usr/lib64/qt5/plugins/kf5/kded/ktimezoned.so
/usr/lib64/qt5/plugins/kf5/kded/soliduiserver.so
/usr/lib64/qt5/plugins/kf5/kded/statusnotifierwatcher.so
/usr/lib64/qt5/plugins/kf5/kio/applications.so
/usr/lib64/qt5/plugins/kf5/kio/desktop.so
/usr/lib64/qt5/plugins/kf5/kio/kio_fonts.so
/usr/lib64/qt5/plugins/kf5/krunner/calculator.so
/usr/lib64/qt5/plugins/kf5/krunner/helprunner.so
/usr/lib64/qt5/plugins/kf5/krunner/kcms/kcm_krunner_kill.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_appstream.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_bookmarksrunner.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_kill.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_placesrunner.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_powerdevil.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_recentdocuments.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_services.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_sessions.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_shell.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_webshortcuts.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_windowedwidgets.so
/usr/lib64/qt5/plugins/kf5/krunner/locations.so
/usr/lib64/qt5/plugins/kf5/parts/kfontviewpart.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/plasma_layouttemplate.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/plasma_lookandfeel.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/plasma_shell.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/plasma_wallpaper.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/wallpaper_images.so
/usr/lib64/qt5/plugins/phonon_platform/kde.so
/usr/lib64/qt5/plugins/plasma/applets/org.kde.plasma.panelspacer.so
/usr/lib64/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
/usr/lib64/qt5/plugins/plasma/applets/org.kde.plasma.systemtray.so
/usr/lib64/qt5/plugins/plasma/applets/plasma_applet_appmenu.so
/usr/lib64/qt5/plugins/plasma/applets/plasma_applet_calendar.so
/usr/lib64/qt5/plugins/plasma/applets/plasma_applet_icon.so
/usr/lib64/qt5/plugins/plasma/applets/plasma_applet_notifications.so
/usr/lib64/qt5/plugins/plasma/applets/plasma_applet_systemmonitor.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_applauncher.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_contextmenu.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_paste.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_switchactivity.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_switchdesktop.so
/usr/lib64/qt5/plugins/plasma/containmentactions/plasma_containmentactions_switchwindow.so
/usr/lib64/qt5/plugins/plasma/dataengine/ion_bbcukmet.so
/usr/lib64/qt5/plugins/plasma/dataengine/ion_dwd.so
/usr/lib64/qt5/plugins/plasma/dataengine/ion_envcan.so
/usr/lib64/qt5/plugins/plasma/dataengine/ion_noaa.so
/usr/lib64/qt5/plugins/plasma/dataengine/ion_wettercom.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_activities.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_applicationjobs.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_apps.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_clipboard.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_devicenotifications.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_dict.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_executable.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_favicons.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_filebrowser.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_geolocation.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_hotplug.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_keystate.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_mouse.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_mpris2.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_notifications.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_packagekit.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_places.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_powermanagement.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_soliddevice.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_statusnotifieritem.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_systemmonitor.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_time.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_weather.so
/usr/lib64/qt5/plugins/plasma/geolocationprovider/plasma-geolocation-ip.so
/usr/lib64/qt5/plugins/plasma/kcminit/kcm_fonts_init.so
/usr/lib64/qt5/plugins/plasma/kcminit/kcm_style_init.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_autostart.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_colors.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_cursortheme.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_desktoptheme.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_fonts.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_formats.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_icons.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_lookandfeel.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_nightcolor.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_notifications.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_style.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_translations.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_users.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_fontinst.so
/usr/lib64/qt5/plugins/plasmacalendarplugins/holidays/HolidaysConfig.qml
/usr/lib64/qt5/plugins/plasmacalendarplugins/holidaysevents.so
/usr/lib64/qt5/qml/org/kde/colorcorrect/libcolorcorrectplugin.so
/usr/lib64/qt5/qml/org/kde/colorcorrect/qmldir
/usr/lib64/qt5/qml/org/kde/holidayeventshelperplugin/libholidayeventshelperplugin.so
/usr/lib64/qt5/qml/org/kde/holidayeventshelperplugin/qmldir
/usr/lib64/qt5/qml/org/kde/notificationmanager/libnotificationmanagerplugin.so
/usr/lib64/qt5/qml/org/kde/notificationmanager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/lookandfeel/liblookandfeelqmlplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/lookandfeel/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/appmenu/libappmenuplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/appmenu/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/BasicAppletContainer.qml
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/ConfigOverlayWithHandles.qml
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/PlaceHolder.qml
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/libcontainmentlayoutmanagerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/private/BasicResizeHandle.qml
/usr/lib64/qt5/qml/org/kde/plasma/private/containmentlayoutmanager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/digitalclock/libdigitalclockplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/digitalclock/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/kicker/libkickerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/kicker/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/sessions/libsessionsprivateplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/sessions/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/shell/libplasmashellprivateplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/shell/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/wallpapers/image/libplasma_wallpaper_imageplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/wallpapers/image/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/workspace/components/BatteryIcon.qml
/usr/lib64/qt5/qml/org/kde/plasma/workspace/components/KeyboardLayoutSwitcher.qml
/usr/lib64/qt5/qml/org/kde/plasma/workspace/components/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/workspace/dialogs/SystemDialog.qml
/usr/lib64/qt5/qml/org/kde/plasma/workspace/dialogs/examples/test.qml
/usr/lib64/qt5/qml/org/kde/plasma/workspace/dialogs/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/workspace/keyboardlayout/libkeyboardlayoutplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/workspace/keyboardlayout/qmldir
/usr/lib64/qt5/qml/org/kde/taskmanager/libtaskmanagerplugin.so
/usr/lib64/qt5/qml/org/kde/taskmanager/qmldir

%files libexec
%defattr(-,root,root,-)
/usr/lib64/libexec/baloorunner
/usr/lib64/libexec/kauth/fontinst
/usr/lib64/libexec/kauth/fontinst_helper
/usr/lib64/libexec/kauth/fontinst_x11
/usr/lib64/libexec/kfontprint
/usr/lib64/libexec/ksmserver-logout-greeter
/usr/lib64/libexec/plasma-changeicons
/usr/lib64/libexec/plasma-dbus-run-session-if-needed
/usr/lib64/libexec/plasma-sourceenv.sh

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/plasma-baloorunner.service
/usr/lib/systemd/user/plasma-core.target
/usr/lib/systemd/user/plasma-gmenudbusmenuproxy.service
/usr/lib/systemd/user/plasma-kcminit-phase1.service
/usr/lib/systemd/user/plasma-kcminit.service
/usr/lib/systemd/user/plasma-krunner.service
/usr/lib/systemd/user/plasma-ksmserver.service
/usr/lib/systemd/user/plasma-ksplash-ready.service
/usr/lib/systemd/user/plasma-ksplash.service
/usr/lib/systemd/user/plasma-plasmashell.service
/usr/lib/systemd/user/plasma-restoresession.service
/usr/lib/systemd/user/plasma-workspace-wayland.target
/usr/lib/systemd/user/plasma-workspace-x11.target
/usr/lib/systemd/user/plasma-workspace.target
/usr/lib/systemd/user/plasma-xembedsniproxy.service
